//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andreeva_TZv2.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BorrowRoom()
        {
            this.BookingHistory = new HashSet<BookingHistory>();
        }
    
        public int ID { get; set; }
        public int Room { get; set; }
        public string Client { get; set; }
        public string Administrotor { get; set; }
        public System.DateTime SettlementDate { get; set; }
        public int CountDay { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingHistory> BookingHistory { get; set; }
        public virtual InfoRoom InfoRoom { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
