//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andreeva_TZv2.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrow_room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public borrow_room()
        {
            this.booking_history = new HashSet<booking_history>();
        }
    
        public int id { get; set; }
        public int room { get; set; }
        public string client { get; set; }
        public int administrator { get; set; }
        public string status { get; set; }
        public int count_day { get; set; }
        public System.DateTime date_settlement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_history> booking_history { get; set; }
        public virtual info_room info_room { get; set; }
        public virtual client client1 { get; set; }
        public virtual user user { get; set; }
    }
}
