//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andreeva_TZv2.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoRoom()
        {
            this.BorrowRoom = new HashSet<BorrowRoom>();
        }
    
        public int NumberRoom { get; set; }
        public int CountRoom { get; set; }
        public int Capacity { get; set; }
        public string TypeRoom { get; set; }
        public double Price { get; set; }
        public string RoomDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowRoom> BorrowRoom { get; set; }
    }
}
